application: thingpool
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
  
- url: /img
  static_dir: static/bootstrap/img
  
- url: /css
  static_dir: static/bootstrap/css
  
- url: /js
  static_dir: static/bootstrap/js
  
- url: /.*
  script: index.app
  
libraries:
- name: jinja2
  version: latest
